version: 2
jobs:
  build:
    macos:
      xcode: "9.3.0"

    steps:
      - checkout
      - run:
          name: Install
          command: bundle install
      - run:
          name: Build
          command: bundle exec fastlane ios beta
