version: 2
jobs:
  build:
    macos:
      xcode: "9.3.0"

    steps:
      - checkout
      
      - run:
          name: Set Ruby Version
          command: echo "ruby-2.3.3" > ~/.ruby-version

      - run:
          name: Install
          command: bundle install


      - run:
          name: Build
          command: bundle exec fastlane ios beta
