# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
  lane :beta do
  	increment_build_number
    match(
      readonly: true,
      type: 'adhoc',
      app_identifier: ''
    )
  	gym(
  		project:'HelloWorldCI.xcodeproj',
  		scheme: 'HelloWorldCI',
  		clean: true,
  		export_method: 'ad-hoc'
  	)
  	hockey(api_token:'e76337ce19d24c34ad48dd935bbe3291')
  	# bundle exec fastlane ios beta
    # add actions here: https://docs.fastlane.tools/actions
  end

end
